# Project
version=1.0.0
group=net.conczin.mca
java_version=21

# Common
minecraft_version=1.21.1
mod_name=Minecraft Comes Alive
mod_author=Luke100000, S0llace, CDAGaming, ffrannny, jahx_senpoopie, WildBamaBoy, SheWolfDeadly
mod_id=mca
mod_homepage=https://conczin.net/
mod_sources=https://github.com/Luke100000/minecraft-comes-alive
mod_issues=https://github.com/Luke100000/minecraft-comes-alive/issues
license=GPL-3.0
description=No more squidward-villagers! Interact with male and female human villagers and online library.
credits=""
minecraft_version_range=[1.21, 1.22)

# Mappings
parchment_minecraft=1.21.1
parchment_version=2024.11.17

# Fabric
mca_dev_username=Dev
fabric_loader_version=0.19.3
loom_version=1.17-SNAPSHOT
fabric_version=0.116.13+1.21.1

# Fabric dev/runtime mods
sodium_version=mc1.21.1-0.8.12-fabric
iris_version=1.8.8+1.21.1-fabric
ferritecore_version=7.0.3-fabric
packetfixer_version=3.3.1

# NeoForge
moddev_version=2.0.141
neo_form_version=1.21.1-20240808.144430
neoforge_version=21.1.234
neoforge_loader_version_range=[1,)

# NeoForge dev/runtime mods
sodium_neoforge_version=mc1.21.1-0.8.12-neoforge
iris_neoforge_version=1.8.12+1.21.1-neoforge
ferritecore_neoforge_version=7.0.3-neoforge
packetfixer_neoforge_version=3.3.1

# Gradle
org.gradle.jvmargs=-Xmx4G --enable-native-access=ALL-UNNAMED
org.gradle.daemon=false
org.gradle.warning.mode=all
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.parallel=true